# Generated by Django 4.0.4 on 2022-07-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=24)),
                ('first', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=24)),
                ('voucher_type', models.TextField(choices=[('30', '30 percent'), ('40', '40 percent'), ('50', '50 percent')])),
                ('voucher_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('Tattoo', 'Tattoo'), ('Henna', 'Henna'), ('Piercing', 'Piercing')], max_length=24)),
                ('service_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ramsched.artistinformation')),
                ('service_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ramsched.clientinformations')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('G', 'Gcash'), ('C', 'Cash'), ('P', 'Paymaya')], max_length=1)),
                ('payment_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ramsched.voucher')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ramsched.service')),
            ],
        ),
    ]
