# Generated by Django 4.0.4 on 2022-07-04 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Ramsched', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='id',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_name',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
